### ISSUE TITLE
Move to Orchard Core Contrib

### ISSUE THREAD

**Issue by hishamco** [agriffard/Disqus.OrchardCore#4]
@agriffard is it fine for you to have this module in Orchard Core Contrib (OCC) while the intention for that organization to have a community-driven module in one place

For sure the credit goes to you :)

**Comment by agriffard** [comment]
No sorry @hishamco, I will keep it there.
It does not do much.
I try do update it regularly.
It is a good example of using Settings in Parts in Orchard Core.

**Comment by hishamco** [comment]
No problem, I might start With Giscus, then create a simplistic version of Disqus
